### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '?'

### ISSUE THREAD

**Issue by galoppi** [OwenMelbz/forget-db#2]
Hi!

When I call `forget-db update` I get an error:

`PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in phar:///usr/local/bin/forget-db/vendor/symfony/console/Output/Output.php on line 40`

This happens on PHP 7.0.30 and PHP 5.6.22.

**Comment by OwenMelbz** [comment]
Hi @galoppi Sorry it's not more clear - I'll list it publically,

But you can see all the platform requirements in the composer file https://github.com/OwenMelbz/forget-db/blob/master/composer.json#L19

You'll need 7.1 on the CLI to run it due to syntax requirements, and active official support for php 7.0 was dropped several months ago

The website itself can run on any version you want, but the binary must run with access to PHP 7.1

**Comment by galoppi** [comment]
Thanks!
